version: '3'

services:
   node:
      container_name: node
      image: codi_node:1.0
      build:
         context: ./
         dockerfile: ./node/node.dockerfile
      ports:
         - 5000:5000
      volumes:
         - ../server:/home/Codieater

   db:
      container_name: pg
      image: codi_db:1.0
      build:
         context: ./
         dockerfile: ./pg/pg.dockerfile
      ports:
         - 5432:5432
      volumes:
         - ./pg/data:/var/lib/postgresql/data

   judge:
      container_name: judge
      image: judge:1.0
      build: 
        context: ./
        dockerfile: ./judge/judge.dockerfile
      volumes:
        - ../judge:/home/judge
