version: '3'

services:
   node:
      container_name: node
      image: codi_node:1.0
      build:
         context: ./
         dockerfile: ./node/node.dockerfile
      ports:
         - 5000:5000
      volumes:
         - ../server:/home/Codieater

   db:
      container_name: pg
      image: codi_db:1.0
      build:
         context: ./
         dockerfile: ./pg/pg.dockerfile
      ports:
         - 5432:5432
      volumes:
         - codi_pg_data:/var/lib/postgresql/data
      environment:
         - POSTGRES_USER=codi
         - POSTGRES_PASSWORD=codicodi
         - LANG=ko_KR.utf8

   judge:
      container_name: judge
      image: judge:1.0
      build: 
        context: ./
        dockerfile: ./judge/judge.dockerfile
      volumes:
        - ../judge:/home/judge
        - ../data/mark_no/2:/home/mark
        - ../data/prob_no/1:/home/prob
      environment:
        - MARKPATH=/home/mark
        - PROBPATH=/home/prob

volumes:
   codi_pg_data:
